### ISSUE TITLE
Possible emergency contact verifcation?

### ISSUE THREAD

**Issue by 74togo** [HomeSafe/homesafe#2]
Is it possible to have a scheme like this:
1. HomeSafe user asks for John Doe to be their emergency contact with phone number XXX.
2. John Doe receives a text message saying "Respond with code XYZ to verify."
3. John Doe replies with XYZ
4. HomeSafe user's phone detects an incoming SMS with code XYZ, therefore adding John Doe to emergency contacts.

**Comment by jahrndez** [comment]
Sounds good. We'll look into the possibility of implementing this.

**Comment by Vivekparam** [comment]
Will not solve
