### ISSUE TITLE
Cannot execute Network Requests on the UI thread -- need to add new threads

### ISSUE THREAD

**Issue by Vivekparam** [HomeSafe/homesafe#3]
This gives an exception when attempted. Android doesnt allow Network calls on the main thread.

**Comment by 74togo** [comment]
Just put all that junk in http://developer.android.com/reference/android/os/AsyncTask.html

That's what I did in my android project here https://github.com/PhearTheCeal/RandomWikiSmmry/blob/master/src/com/pheartheceal/randomwikisummary/MainActivity.java#L69

**Comment by Vivekparam** [comment]
Running this on a separate thread with callback has been implemented. See GoogleMapsUtils.
